name: patox
description: 'govengquizox'
version: 1.0.15+17

publish_to: 'none'
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  chopper: ^4.0.5
  provider: ^6.0.3
  path_provider: ^2.0.11
  flutter_inappwebview: ^5.4.0
  flutter_svg: ^1.1.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  introduction_screen: ^3.0.2
  url_launcher: ^6.1.3
  intl: any
  logger: ^1.1.0
  jwt_decoder: ^2.0.1
  firebase_core: ^1.24.0
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^13.0.4
  flutter_local_notifications: ^9.6.1
  permission_handler: ^10.0.0
  flutter_downloader: ^1.8.3
  cupertino_icons: ^1.0.2
  in_app_purchase: ^3.1.1
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  chopper_generator: ^4.0.5
  json_serializable: ^6.5.4
  flutter_native_splash: ^2.2.15
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/splashIcon.png
    - assets/images/splashBG.png

flutter_icons:
  android: 'ic_launcher'
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/icon.png'
  min_sdk_android: 21

flutter_native_splash:
  background_image: "assets/images/splashBG.png"
  background_image_dark: "assets/images/splashBG.png"

  android_12:
    image: assets/images/splashIcon.png
    color: "#0085F5"
    icon_background_color: "#0085F5"
    image_dark: assets/images/splashIcon.png
    color_dark: "#0085F5"
    icon_background_color_dark: "#0085F5"

  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
